"""empty message

Revision ID: 1c1ecb8a5de6
Revises: 1115ef8a0abb
Create Date: 2025-11-18 23:19:58.266854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c1ecb8a5de6'
down_revision = '1115ef8a0abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vegetable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_vegetable_catagory_id_vegetable_category'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_vegetable_category_id_vegetable_category'), 'vegetable_category', ['category_id'], ['id'])
        batch_op.drop_column('catagory_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vegetable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catagory_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_vegetable_category_id_vegetable_category'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_vegetable_catagory_id_vegetable_category'), 'vegetable_category', ['catagory_id'], ['id'])
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
