"""empty message

Revision ID: 423fe8d2fb81
Revises: 
Create Date: 2025-11-18 20:22:37.814878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423fe8d2fb81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_table('vegetable_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vegetable_category'))
    )
    op.create_table('vegetable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('picture', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.String(length=100), nullable=False),
    sa.Column('place', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('pun_day', sa.DateTime(), nullable=False),
    sa.Column('catagory_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catagory_id'], ['vegetable_category.id'], name=op.f('fk_vegetable_catagory_id_vegetable_category')),
    sa.ForeignKeyConstraint(['publisher_id'], ['user.id'], name=op.f('fk_vegetable_publisher_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vegetable'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vegetable')
    op.drop_table('vegetable_category')
    op.drop_table('user')
    # ### end Alembic commands ###
