"""empty message

Revision ID: bd3a7c1b8422
Revises: 4c3c9aa3383f
Create Date: 2025-11-20 15:17:10.487422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd3a7c1b8422'
down_revision = '4c3c9aa3383f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vegetable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pun_data', sa.DateTime(), nullable=False))
        batch_op.drop_column('pun_day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vegetable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pun_day', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('pun_data')

    # ### end Alembic commands ###
