"""empty message

Revision ID: d785325072cc
Revises: bd3a7c1b8422
Create Date: 2025-11-20 15:25:06.442375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd785325072cc'
down_revision = 'bd3a7c1b8422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vegetable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pub_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('pun_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vegetable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pun_data', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('pub_date')

    # ### end Alembic commands ###
